//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a4fdf1_basiEntities1 : DbContext
    {
        public db_a4fdf1_basiEntities1()
            : base("name=db_a4fdf1_basiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_cliente> tb_cliente { get; set; }
        public virtual DbSet<tb_conta> tb_conta { get; set; }
        public virtual DbSet<tb_controleponto> tb_controleponto { get; set; }
        public virtual DbSet<tb_descontos> tb_descontos { get; set; }
        public virtual DbSet<tb_despesa> tb_despesa { get; set; }
        public virtual DbSet<tb_estoque> tb_estoque { get; set; }
        public virtual DbSet<tb_folha> tb_folha { get; set; }
        public virtual DbSet<tb_forncedor> tb_forncedor { get; set; }
        public virtual DbSet<tb_funcionario> tb_funcionario { get; set; }
        public virtual DbSet<tb_hora_extra> tb_hora_extra { get; set; }
        public virtual DbSet<tb_login> tb_login { get; set; }
        public virtual DbSet<tb_pedido_compra> tb_pedido_compra { get; set; }
        public virtual DbSet<tb_pedido_compra_item> tb_pedido_compra_item { get; set; }
        public virtual DbSet<tb_pedido_venda> tb_pedido_venda { get; set; }
        public virtual DbSet<tb_pedido_venda_item> tb_pedido_venda_item { get; set; }
        public virtual DbSet<tb_produto> tb_produto { get; set; }
        public virtual DbSet<tb_provento> tb_provento { get; set; }
    }
}
