//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cliente()
        {
            this.tb_pedido_venda = new HashSet<tb_pedido_venda>();
        }
    
        public int id_cliente { get; set; }
        public string nm_cliente { get; set; }
        public string nm_endereco { get; set; }
        public string nm_cidade { get; set; }
        public string nm_email { get; set; }
        public string vl_cpf { get; set; }
        public string vl_tel { get; set; }
        public int vl_cep { get; set; }
        public string sexo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_venda> tb_pedido_venda { get; set; }
    }
}
