//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_conta
    {
        public int id_Conta { get; set; }
        public int id_fornecedor { get; set; }
        public string nm_referente { get; set; }
        public System.DateTime dt_emissao { get; set; }
        public System.DateTime dt_venc_pago { get; set; }
        public byte[] ContaPagar { get; set; }
        public byte[] ContaReceber { get; set; }
        public bool bl_PagarReceber { get; set; }
        public decimal vl_conta { get; set; }
    
        public virtual tb_forncedor tb_forncedor { get; set; }
    }
}
