//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_controleponto
    {
        public int id_ControlePonto { get; set; }
        public int id_funcionario { get; set; }
        public System.DateTime dt_entrada { get; set; }
        public System.TimeSpan dt_entrada_almoco { get; set; }
        public System.TimeSpan dt_saida_almoco { get; set; }
        public System.DateTime dt_saida { get; set; }
        public System.DateTime dt_data { get; set; }
        public int vl_faltas { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
