//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_despesa
    {
        public int id_FluxAux { get; set; }
        public int id_Funcinario { get; set; }
        public int id_Estoque { get; set; }
        public decimal vl_Despesa { get; set; }
    
        public virtual tb_estoque tb_estoque { get; set; }
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
