//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_descontos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_descontos()
        {
            this.tb_folha = new HashSet<tb_folha>();
        }
    
        public int id_descontos { get; set; }
        public int id_funcionario { get; set; }
        public decimal vl_inss { get; set; }
        public Nullable<decimal> vl_ir { get; set; }
        public Nullable<decimal> vl_va { get; set; }
        public Nullable<decimal> vl_vr { get; set; }
        public Nullable<decimal> vl_vt { get; set; }
        public Nullable<decimal> vl_planosaude { get; set; }
        public Nullable<decimal> vl_planoodonto { get; set; }
        public Nullable<decimal> vl_segurodevida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_folha> tb_folha { get; set; }
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
