//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_estoque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_estoque()
        {
            this.tb_despesa = new HashSet<tb_despesa>();
        }
    
        public int id_estoque { get; set; }
        public int id_forncedor { get; set; }
        public int id_produto { get; set; }
        public int qnt_produto { get; set; }
        public System.DateTime dt_entrada { get; set; }
        public System.DateTime dt_saida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_despesa> tb_despesa { get; set; }
        public virtual tb_forncedor tb_forncedor { get; set; }
        public virtual tb_produto tb_produto { get; set; }
    }
}
