//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_forncedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_forncedor()
        {
            this.tb_conta = new HashSet<tb_conta>();
            this.tb_estoque = new HashSet<tb_estoque>();
            this.tb_pedido_compra = new HashSet<tb_pedido_compra>();
        }
    
        public int id_Forncedor { get; set; }
        public string nm_Fornecedor { get; set; }
        public string nm_endereco { get; set; }
        public string nm_cidade { get; set; }
        public string nm_email { get; set; }
        public int vl_tel { get; set; }
        public string cnpj { get; set; }
        public string cpf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_conta> tb_conta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_compra> tb_pedido_compra { get; set; }
    }
}
