//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_folha
    {
        public int id_folha { get; set; }
        public int id_descontos { get; set; }
        public int id_funcionario { get; set; }
        public int id_proventos { get; set; }
        public decimal vl_valorBruto { get; set; }
        public decimal vl_valorLiquido { get; set; }
        public bool bl_ferias { get; set; }
        public bool bl_venderFerias { get; set; }
        public bool bl_13salario { get; set; }
    
        public virtual tb_descontos tb_descontos { get; set; }
        public virtual tb_funcionario tb_funcionario { get; set; }
        public virtual tb_provento tb_provento { get; set; }
    }
}
