//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_pedido_compra()
        {
            this.tb_pedido_compra_item = new HashSet<tb_pedido_compra_item>();
        }
    
        public int id_pedido_compra { get; set; }
        public int id_Fornecedor { get; set; }
        public System.DateTime dt_Compra { get; set; }
        public byte[] ContaPagar { get; set; }
        public System.DateTime dt_vencimento { get; set; }
        public System.DateTime dt_emissao { get; set; }
    
        public virtual tb_forncedor tb_forncedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_compra_item> tb_pedido_compra_item { get; set; }
    }
}
