//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_provento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_provento()
        {
            this.tb_folha = new HashSet<tb_folha>();
        }
    
        public int id_provento { get; set; }
        public System.DateTime dt_horasextras { get; set; }
        public System.DateTime dt_adicnoturno { get; set; }
        public decimal vl_Perioclosidade { get; set; }
        public decimal vl_Insulibridade { get; set; }
        public decimal vl_Gratificacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_folha> tb_folha { get; set; }
    }
}
