//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bistro.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_produto()
        {
            this.tb_estoque = new HashSet<tb_estoque>();
            this.tb_pedido_compra_item = new HashSet<tb_pedido_compra_item>();
            this.tb_pedido_venda_item = new HashSet<tb_pedido_venda_item>();
        }
    
        public int id_produto { get; set; }
        public string nm_produto { get; set; }
        public string nm_marca { get; set; }
        public string nm_categoria { get; set; }
        public decimal vl_preco { get; set; }
        public string nm_lote { get; set; }
        public System.DateTime dt_validade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_compra_item> tb_pedido_compra_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_venda_item> tb_pedido_venda_item { get; set; }
    }
}
